str1 = input("Enter first String : ")
str2 = input("Enter Second String : ")
print(str1)
print(str2)
print("Convert first String into lower case :")
print(str1.lower())
print("Convert first String into upper case :")
print(str1.upper())
print("Add two Strings :")
print(str1 + str2)
print("Length of first string :")
print(len(str1))
print("Length of Second string :")
print(len(str2))
print(f"{str1} {str2}")
